/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    sites: Site;
    media: Media;
    pages: Page;
    posts: Post;
    'service-sections': ServiceSection;
    products: Product;
    solutions: Solution;
    'case-studies': CaseStudy;
    faqs: Faq;
    menus: Menu;
    forms: Form;
    'form-submissions': FormSubmission;
    'prompt-sets': PromptSet;
    redirects: Redirect;
    'chat-sessions': ChatSession;
    'chat-users': ChatUser;
    'chat-usage': ChatUsage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'service-sections': ServiceSectionsSelect<false> | ServiceSectionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'prompt-sets': PromptSetsSelect<false> | PromptSetsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'chat-sessions': ChatSessionsSelect<false> | ChatSessionsSelect<true>;
    'chat-users': ChatUsersSelect<false> | ChatUsersSelect<true>;
    'chat-usage': ChatUsageSelect<false> | ChatUsageSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  fullName?: string | null;
  role: 'super_admin' | 'site_admin' | 'editor' | 'reviewer' | 'publisher';
  /**
   * Site codes this user may manage (ignored for super_admin).
   */
  allowedSiteCodes?: string[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: string;
  /**
   * Stable site code, e.g. corporate, xbooking.
   */
  code: string;
  name: string;
  /**
   * Host used to resolve this site in production, e.g. xbooking.vn.
   */
  primaryDomain?: string | null;
  product?: string | null;
  tagline?: string | null;
  theme?: {
    primary?: string | null;
    accent?: string | null;
    surface?: string | null;
    style?: string | null;
  };
  chatbotConfig?: {
    enabled?: boolean | null;
    welcome?: string | null;
    defaultPrompts?: string[] | null;
  };
  /**
   * draft → review → approved → published → archived
   */
  status: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alt text is mandatory for accessibility (docs/04).
   */
  alt: string;
  caption?: string | null;
  source?: string | null;
  /**
   * Leave empty for assets shared across all sites.
   */
  site?: (string | null) | Site;
  /**
   * Mark AI-generated imagery (do not auto-publish, docs/CLAUDE rule 10).
   */
  aiGenerated?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  site: string | Site;
  /**
   * Auto-filled from the selected site.
   */
  siteCode?: string | null;
  /**
   * Path within the site, leading slash included (e.g. /san-pham/xai).
   */
  slug: string;
  title: string;
  pageType: 'home' | 'landing' | 'product' | 'solution' | 'article_index' | 'form' | 'legal';
  locale: string;
  /**
   * Page summary; also the chatbot context (max 1500 chars).
   */
  summary?: string | null;
  blocks?:
    | (
        | HeroBlock
        | RichTextBlock
        | FeatureGridBlock
        | ProductCardsBlock
        | SolutionCardsBlock
        | PainPointsBlock
        | ProcessTimelineBlock
        | StatisticsBlock
        | ScreenshotsBlock
        | ArchitectureBlock
        | ComparisonTableBlock
        | IntegrationBlock
        | CaseStudyCardsBlock
        | FaqBlock
        | RelatedInsightsBlock
        | DeploymentCardsBlock
        | LeadFormBlock
        | CTABlock
      )[]
    | null;
  /**
   * Metadata for search engines and social sharing.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    index?: boolean | null;
    follow?: boolean | null;
    canonical?: string | null;
    ogImage?: (string | null) | Media;
  };
  suggestedPrompts?: string[] | null;
  /**
   * Up to a handful of related pages for the chatbot to suggest.
   */
  relatedPages?: (string | Page)[] | null;
  /**
   * draft → review → approved → published → archived
   */
  status: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  primaryCTA: {
    label: string;
    href: string;
  };
  secondaryCTA: {
    label: string;
    href: string;
  };
  illustration?: (string | null) | Media;
  /**
   * Ảnh nền phủ kín khu vực hero/first-fold. Nội dung hero vẫn giữ nguyên phía trên; có lớp overlay để đảm bảo tương phản chữ.
   */
  background?: (string | null) | Media;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  title?: string | null;
  intro?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  illustration?: (string | null) | Media;
  /**
   * Đường dẫn ảnh minh họa (public path, vd /products/xai/xai-04-...png) hiển thị cạnh lưới.
   */
  imageSrc?: string | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductCardsBlock".
 */
export interface ProductCardsBlock {
  title?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  illustration?: (string | null) | Media;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionCardsBlock".
 */
export interface SolutionCardsBlock {
  title?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'solutionCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PainPointsBlock".
 */
export interface PainPointsBlock {
  title?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'painPoints';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessTimelineBlock".
 */
export interface ProcessTimelineBlock {
  title?: string | null;
  steps: string[];
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processTimeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatisticsBlock".
 */
export interface StatisticsBlock {
  title?: string | null;
  items?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statistics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScreenshotsBlock".
 */
export interface ScreenshotsBlock {
  title?: string | null;
  items?:
    | {
        media?: (string | null) | Media;
        alt: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'screenshots';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchitectureBlock".
 */
export interface ArchitectureBlock {
  title?: string | null;
  layers?:
    | {
        name: string;
        items: string[];
        id?: string | null;
      }[]
    | null;
  illustration?: (string | null) | Media;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'architecture';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock".
 */
export interface ComparisonTableBlock {
  title?: string | null;
  columns: string[];
  /**
   * Each row holds one cell per column.
   */
  rows?:
    | {
        cells: string[];
        id?: string | null;
      }[]
    | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparisonTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationBlock".
 */
export interface IntegrationBlock {
  title?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'integration';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCardsBlock".
 */
export interface CaseStudyCardsBlock {
  title?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'caseStudyCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  title?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedInsightsBlock".
 */
export interface RelatedInsightsBlock {
  title?: string | null;
  items?:
    | {
        title: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedInsights';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DeploymentCardsBlock".
 */
export interface DeploymentCardsBlock {
  title?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  illustration?: (string | null) | Media;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'deploymentCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadFormBlock".
 */
export interface LeadFormBlock {
  title?: string | null;
  /**
   * References Forms.code (e.g. demo-request, contact).
   */
  formCode: string;
  fields?: string[] | null;
  illustration?: (string | null) | Media;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'leadForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  title: string;
  description?: string | null;
  primaryCTA: {
    label: string;
    href: string;
  };
  secondaryCTA: {
    label: string;
    href: string;
  };
  illustration?: (string | null) | Media;
  /**
   * Stable anchor so the chatbot can deep-link to this section.
   */
  anchorId?: string | null;
  theme?: ('light' | 'soft' | 'dark' | 'brand') | null;
  padding?: ('compact' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  site: string | Site;
  /**
   * Auto-filled from the selected site.
   */
  siteCode?: string | null;
  slug: string;
  title: string;
  /**
   * Bài thuộc mục Insights (/insights) hay Tin tức (/tin-tuc).
   */
  section?: ('insight' | 'news' | 'archive') | null;
  excerpt?: string | null;
  category?: string | null;
  /**
   * Ảnh bìa / thumbnail (tải lên). Nếu để trống sẽ dùng Cover URL.
   */
  cover?: (string | null) | Media;
  /**
   * Đường dẫn ảnh bìa mặc định (khi chưa tải ảnh lên).
   */
  coverUrl?: string | null;
  /**
   * Vd: "6 phút đọc".
   */
  readTime?: string | null;
  /**
   * Ngày hiển thị, vd: "24/07/2026".
   */
  date?: string | null;
  featured?: boolean | null;
  /**
   * Slug/tên sản phẩm liên quan để gợi ý cuối bài.
   */
  relatedProducts?: string[] | null;
  /**
   * Chủ đề để lọc/liệt kê bài viết. Mỗi tag là một mục; click tag trên site sẽ mở /insights/tag/<tag>. Vd: AI, Dữ liệu, Cloud, Security, PropTech.
   */
  tags?: string[] | null;
  locale: string;
  /**
   * Structured body nodes: [{ type: paragraph|heading, text }].
   */
  body?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Metadata for search engines and social sharing.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    index?: boolean | null;
    follow?: boolean | null;
    canonical?: string | null;
    ogImage?: (string | null) | Media;
  };
  author?: (string | null) | User;
  reviewer?: (string | null) | User;
  /**
   * draft → review → approved → published → archived
   */
  status: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-sections".
 */
export interface ServiceSection {
  id: string;
  site: string | Site;
  /**
   * Auto-filled from the selected site.
   */
  siteCode?: string | null;
  sectionId: string;
  /**
   * Kiểu bố cục hiển thị (component tương ứng dựng layout).
   */
  visualType:
    | 'hub-spoke'
    | 'maturity-radar'
    | 'architecture-stack'
    | 'process-evolution'
    | 'data-platform'
    | 'integration-hub'
    | 'adoption-journey'
    | 'control-tower';
  eyebrow?: string | null;
  title: string;
  subtitle?: string | null;
  /**
   * Các path hiển thị section này, vd: /dich-vu/chuyen-doi-so
   */
  routes: string[];
  /**
   * Thứ tự trong một route (tăng dần).
   */
  order?: number | null;
  items?:
    | {
        itemId: string;
        order?: number | null;
        title: string;
        description: string;
        side?: ('left' | 'right' | 'top' | 'bottom') | null;
        /**
         * Tên icon lucide (kebab-case), tùy chọn.
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        itemId: string;
        order?: number | null;
        title: string;
        description: string;
        side?: ('left' | 'right' | 'top' | 'bottom') | null;
        /**
         * Tên icon lucide (kebab-case), tùy chọn.
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  outcomes?:
    | {
        itemId: string;
        title: string;
        description: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  locale: string;
  /**
   * draft → review → approved → published → archived
   */
  status: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  code: string;
  tagline?: string | null;
  description?: string | null;
  logo?: (string | null) | Media;
  href?: string | null;
  /**
   * draft → review → approved → published → archived
   */
  status: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: string;
  site?: (string | null) | Site;
  /**
   * Auto-filled from the selected site.
   */
  siteCode?: string | null;
  title: string;
  slug: string;
  /**
   * Đường dẫn trang, vd /giai-phap/du-lieu-va-ai hoặc /bo-giai-phap-x
   */
  route?: string | null;
  eyebrow?: string | null;
  summary?: string | null;
  /**
   * Ảnh nền hero (tùy chọn; để trống dùng nền mặc định).
   */
  heroImage?: (string | null) | Media;
  category?: ('chuoi-nghiep-vu' | 'doi-tuong' | 'muc-tieu') | null;
  /**
   * Slug sản phẩm liên quan: x-ai, xbooking, finerp, xbuilding, x-space.
   */
  relatedProducts?: string[] | null;
  /**
   * Các section của trang giải pháp (theo thứ tự hiển thị).
   */
  sections?:
    | {
        sectionId?: string | null;
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        layout?: ('grid' | 'visual-right' | 'visual-left' | 'chips' | 'steps') | null;
        image?: (string | null) | Media;
        items?:
          | {
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaImage?: (string | null) | Media;
  /**
   * draft → review → approved → published → archived
   */
  status: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  site?: (string | null) | Site;
  /**
   * Auto-filled from the selected site.
   */
  siteCode?: string | null;
  title: string;
  slug: string;
  client?: string | null;
  challenge?: string | null;
  solution?: string | null;
  architecture?: string | null;
  results?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  cover?: (string | null) | Media;
  /**
   * draft → review → approved → published → archived
   */
  status: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  site?: (string | null) | Site;
  /**
   * Auto-filled from the selected site.
   */
  siteCode?: string | null;
  question: string;
  answer: string;
  tags?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: string;
  site: string | Site;
  /**
   * Auto-filled from the selected site.
   */
  siteCode?: string | null;
  code: string;
  locale: string;
  /**
   * Nested menu tree: [{ label, href, children?: [...] }].
   */
  items:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  code: string;
  name: string;
  /**
   * Site codes this form is available on.
   */
  siteScope?: string[] | null;
  /**
   * Ordered field keys (resolved via FIELD_LIBRARY in @x/shared-types).
   */
  fields?: string[] | null;
  successMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  site?: (string | null) | Site;
  page?: (string | null) | Page;
  visitorSession?: string | null;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  consent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-sets".
 */
export interface PromptSet {
  id: string;
  site: string | Site;
  /**
   * Auto-filled from the selected site.
   */
  siteCode?: string | null;
  code: string;
  prompts?:
    | {
        label: string;
        prompt: string;
        actionType?: ('ask' | 'navigate' | 'page' | 'demo') | null;
        enabled?: boolean | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  site: string | Site;
  /**
   * Auto-filled from the selected site.
   */
  siteCode?: string | null;
  sourcePath: string;
  destinationPath: string;
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-sessions".
 */
export interface ChatSession {
  id: string;
  deviceId: string;
  sessionId: string;
  title?: string | null;
  siteCode?: string | null;
  lastRoute?: string | null;
  messages:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  messageCount?: number | null;
  provider?: string | null;
  model?: string | null;
  tokensIn?: number | null;
  tokensOut?: number | null;
  /**
   * Chi phí tạm tính (USD) của phiên.
   */
  estCostUsd?: number | null;
  hiddenByUser?: boolean | null;
  /**
   * Đánh dấu hội thoại chất lượng để khai thác làm nội dung bài viết.
   */
  flaggedQuality?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-users".
 */
export interface ChatUser {
  id: string;
  deviceId: string;
  email: string;
  phone: string;
  name?: string | null;
  siteCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-usage".
 */
export interface ChatUsage {
  id: string;
  key: string;
  day?: string | null;
  provider?: string | null;
  model?: string | null;
  requests?: number | null;
  tokensIn?: number | null;
  tokensOut?: number | null;
  /**
   * Chi phí tạm tính (USD).
   */
  estCostUsd?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'sites';
        value: string | Site;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'service-sections';
        value: string | ServiceSection;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'solutions';
        value: string | Solution;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'menus';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'prompt-sets';
        value: string | PromptSet;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'chat-sessions';
        value: string | ChatSession;
      } | null)
    | ({
        relationTo: 'chat-users';
        value: string | ChatUser;
      } | null)
    | ({
        relationTo: 'chat-usage';
        value: string | ChatUsage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  allowedSiteCodes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  primaryDomain?: T;
  product?: T;
  tagline?: T;
  theme?:
    | T
    | {
        primary?: T;
        accent?: T;
        surface?: T;
        style?: T;
      };
  chatbotConfig?:
    | T
    | {
        enabled?: T;
        welcome?: T;
        defaultPrompts?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  source?: T;
  site?: T;
  aiGenerated?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  siteCode?: T;
  slug?: T;
  title?: T;
  pageType?: T;
  locale?: T;
  summary?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        productCards?: T | ProductCardsBlockSelect<T>;
        solutionCards?: T | SolutionCardsBlockSelect<T>;
        painPoints?: T | PainPointsBlockSelect<T>;
        processTimeline?: T | ProcessTimelineBlockSelect<T>;
        statistics?: T | StatisticsBlockSelect<T>;
        screenshots?: T | ScreenshotsBlockSelect<T>;
        architecture?: T | ArchitectureBlockSelect<T>;
        comparisonTable?: T | ComparisonTableBlockSelect<T>;
        integration?: T | IntegrationBlockSelect<T>;
        caseStudyCards?: T | CaseStudyCardsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        relatedInsights?: T | RelatedInsightsBlockSelect<T>;
        deploymentCards?: T | DeploymentCardsBlockSelect<T>;
        leadForm?: T | LeadFormBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        index?: T;
        follow?: T;
        canonical?: T;
        ogImage?: T;
      };
  suggestedPrompts?: T;
  relatedPages?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
      };
  illustration?: T;
  background?: T;
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  illustration?: T;
  imageSrc?: T;
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductCardsBlock_select".
 */
export interface ProductCardsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  illustration?: T;
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionCardsBlock_select".
 */
export interface SolutionCardsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PainPointsBlock_select".
 */
export interface PainPointsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessTimelineBlock_select".
 */
export interface ProcessTimelineBlockSelect<T extends boolean = true> {
  title?: T;
  steps?: T;
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatisticsBlock_select".
 */
export interface StatisticsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScreenshotsBlock_select".
 */
export interface ScreenshotsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        media?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchitectureBlock_select".
 */
export interface ArchitectureBlockSelect<T extends boolean = true> {
  title?: T;
  layers?:
    | T
    | {
        name?: T;
        items?: T;
        id?: T;
      };
  illustration?: T;
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock_select".
 */
export interface ComparisonTableBlockSelect<T extends boolean = true> {
  title?: T;
  columns?: T;
  rows?:
    | T
    | {
        cells?: T;
        id?: T;
      };
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationBlock_select".
 */
export interface IntegrationBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCardsBlock_select".
 */
export interface CaseStudyCardsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedInsightsBlock_select".
 */
export interface RelatedInsightsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        href?: T;
        id?: T;
      };
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DeploymentCardsBlock_select".
 */
export interface DeploymentCardsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  illustration?: T;
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadFormBlock_select".
 */
export interface LeadFormBlockSelect<T extends boolean = true> {
  title?: T;
  formCode?: T;
  fields?: T;
  illustration?: T;
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
      };
  illustration?: T;
  anchorId?: T;
  theme?: T;
  padding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  site?: T;
  siteCode?: T;
  slug?: T;
  title?: T;
  section?: T;
  excerpt?: T;
  category?: T;
  cover?: T;
  coverUrl?: T;
  readTime?: T;
  date?: T;
  featured?: T;
  relatedProducts?: T;
  tags?: T;
  locale?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        index?: T;
        follow?: T;
        canonical?: T;
        ogImage?: T;
      };
  author?: T;
  reviewer?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-sections_select".
 */
export interface ServiceSectionsSelect<T extends boolean = true> {
  site?: T;
  siteCode?: T;
  sectionId?: T;
  visualType?: T;
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  routes?: T;
  order?: T;
  items?:
    | T
    | {
        itemId?: T;
        order?: T;
        title?: T;
        description?: T;
        side?: T;
        icon?: T;
        id?: T;
      };
  process?:
    | T
    | {
        itemId?: T;
        order?: T;
        title?: T;
        description?: T;
        side?: T;
        icon?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        itemId?: T;
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  locale?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  href?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  site?: T;
  siteCode?: T;
  title?: T;
  slug?: T;
  route?: T;
  eyebrow?: T;
  summary?: T;
  heroImage?: T;
  category?: T;
  relatedProducts?: T;
  sections?:
    | T
    | {
        sectionId?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        layout?: T;
        image?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  ctaTitle?: T;
  ctaDescription?: T;
  ctaImage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  site?: T;
  siteCode?: T;
  title?: T;
  slug?: T;
  client?: T;
  challenge?: T;
  solution?: T;
  architecture?: T;
  results?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  cover?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  site?: T;
  siteCode?: T;
  question?: T;
  answer?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  site?: T;
  siteCode?: T;
  code?: T;
  locale?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  siteScope?: T;
  fields?: T;
  successMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  site?: T;
  page?: T;
  visitorSession?: T;
  payload?: T;
  utm?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-sets_select".
 */
export interface PromptSetsSelect<T extends boolean = true> {
  site?: T;
  siteCode?: T;
  code?: T;
  prompts?:
    | T
    | {
        label?: T;
        prompt?: T;
        actionType?: T;
        enabled?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  site?: T;
  siteCode?: T;
  sourcePath?: T;
  destinationPath?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-sessions_select".
 */
export interface ChatSessionsSelect<T extends boolean = true> {
  deviceId?: T;
  sessionId?: T;
  title?: T;
  siteCode?: T;
  lastRoute?: T;
  messages?: T;
  messageCount?: T;
  provider?: T;
  model?: T;
  tokensIn?: T;
  tokensOut?: T;
  estCostUsd?: T;
  hiddenByUser?: T;
  flaggedQuality?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-users_select".
 */
export interface ChatUsersSelect<T extends boolean = true> {
  deviceId?: T;
  email?: T;
  phone?: T;
  name?: T;
  siteCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-usage_select".
 */
export interface ChatUsageSelect<T extends boolean = true> {
  key?: T;
  day?: T;
  provider?: T;
  model?: T;
  requests?: T;
  tokensIn?: T;
  tokensOut?: T;
  estCostUsd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}